services:
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5432:5432"
  kafka:
    image: apache/kafka:3.7.1
    ports:
      - "9092:9092"